name: pizza_time
dependencies:
- binstar=0.10.1=py27_2
- cairo=1.12.18=0
- clyent=0.3.4=py27_0
- dateutil=2.4.1=py27_0
- docutils=0.12=py27_0
- freetype=2.4.10=0
- glueviz=0.4.0=np19py27_0
- ipython=3.0.0=py27_0
- ipython-notebook=3.0.0=py27_1
- ipython-qtconsole=3.0.0=py27_0
- jinja2=2.7.3=py27_1
- jsonschema=2.4.0=py27_0
- launcher=1.0.0=1
- libpng=1.5.13=1
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_0
- mistune=0.5.1=py27_0
- nltk=3.0.2=np19py27_0
- node-webkit=0.10.1=0
- nose=1.3.4=py27_1
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.15.2=np19py27_0
- patsy=0.3.0=np19py27_0
- pip=6.0.8=py27_0
- pixman=0.26.2=0
- ptyprocess=0.4=py27_0
- py2cairo=1.10.0=py27_2
- pydot=1.0.28=py27_0
- pygments=2.0.2=py27_0
- pyparsing=1.5.6=py27_0
- pyqt=4.10.4=py27_0
- python=2.7.9=2
- pytz=2014.9=py27_0
- pyyaml=3.11=py27_0
- pyzmq=14.5.0=py27_0
- qt=4.8.5=0
- readline=6.2=2
- requests=2.5.3=py27_0
- scikit-learn=0.15.2=np19py27_0
- scipy=0.15.1=np19py27_0
- seaborn=0.5.1=np19py27_0
- setuptools=14.0=py27_0
- sip=4.15.5=py27_0
- six=1.9.0=py27_0
- sphinx=1.2.3=py27_0
- spyder=2.3.3=py27_0
- spyder-app=2.3.3=py27_0
- sqlite=3.8.4.1=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- system=5.8=1
- terminado=0.5=py27_0
- tk=8.5.15=0
- tornado=4.1=py27_0
- yaml=0.1.4=0
- zeromq=4.0.4=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - lda==1.0.2
  - pbr==0.10.8
  - python-dateutil==2.4.1

